name: R-CMD-check
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install deps
        run: Rscript -e 'install.packages(c("tidyverse","lubridate","lazyeval"))'
      - name: Session info
        run: Rscript -e 'sessionInfo()'


